#!/bin/sh
if [ -d "node_modules/rc-select" ]; then
    rm -rf node_modules/antd/node_modules/rc-select
    cp -r node_modules/rc-select node_modules/antd/node_modules/
    rm -rf node_modules/rc-select
fi

rm -rf node_modules/antd/lib/mention \
       node_modules/antd/lib/carousel \
       node_modules/antd/lib/transfer \
       node_modules/antd/lib/breadcrumb \
       node_modules/antd/lib/version \
       node_modules/antd/lib/avatar \
       node_modules/antd/lib/timeline \
       node_modules/antd/es/mention \
       node_modules/antd/es/carousel \
       node_modules/antd/es/transfer \
       node_modules/antd/es/breadcrumb \
       node_modules/antd/es/version \
       node_modules/antd/es/avatar \
       node_modules/antd/es/timeline \
       node_modules/draft-js \
       node_modules/react-slick \
       node_modules/rc-editor-mention \

sed -i.bak '/.*mention.*/d' node_modules/antd/es/index.js
sed -i.bak '/.*carousel.*/d' node_modules/antd/es/index.js
sed -i.bak '/.*transfer.*/d' node_modules/antd/es/index.js
sed -i.bak '/.*breadcrumb.*/d' node_modules/antd/es/index.js
sed -i.bak '/.*version.*/d' node_modules/antd/es/index.js
sed -i.bak '/.*avatar.*/d' node_modules/antd/es/index.js
sed -i.bak '/.*timeline.*/d' node_modules/antd/es/index.js