export const LOAD_NET_WORTH_YEAR = "LOAD_NET_WORTH_YEAR";
export const REFRESH_NET_WORTH_YEAR = "REFRESH_NET_WORTH_YEAR";
export const NET_WORTH_YEAR_LOADED = "NET_WORTH_YEAR_LOADED";
export const NET_WORTH_REQUEST_FINISHED = "NET_WORTH_REQUEST_FINISHED";

export const NET_WORTH_ITEMS_IMPORTED = "NET_WORTH_ITEMS_IMPORTED";
export const NET_WORTH_ASSET_ADDED = "NET_WORTH_ASSET_ADDED";
export const NET_WORTH_ASSET_UPDATED = "NET_WORTH_ASSET_UPDATED";
export const NET_WORTH_ASSET_DELETED = "NET_WORTH_ASSET_DELETED";

export const NET_WORTH_ITEM_ADDED = "NET_WORTH_ITEM_ADDED";
export const NET_WORTH_ITEM_UPDATED = "NET_WORTH_ITEM_UPDATED";
export const NET_WORTH_ITEM_DELETED = "NET_WORTH_ITEM_DELETED";
