export const LOAD_BUDGET = "LOAD_BUDGET";
export const REFRESH_BUDGET = "REFRESH_BUDGET";
export const BUDGET_LOADED = "BUDGET_LOADED";
export const BUDGET_REQUEST_FINISHED = "BUDGET_REQUEST_FINISHED";

export const BUDGET_INCOME_UPDATED = "BUDGET_INCOME_UPDATED";
export const BUDGET_CATEGORY_UPDATED = "BUDGET_CATEGORY_UPDATED";
export const BUDGET_CATEGORY_IMPORTED = "BUDGET_CATEGORY_IMPORTED";
export const BUDGET_DATE_UPDATED = "BUDGET_DATE_UPDATED";

export const BUDGET_ITEM_NEW = "BUDGET_ITEM_NEW";
export const BUDGET_ITEM_SAVED = "BUDGET_ITEM_SAVED";
export const BUDGET_ITEM_UPDATED = "BUDGET_ITEM_UPDATED";
export const BUDGET_ITEM_DELETED = "BUDGET_ITEM_DELETED";
export const BUDGET_ITEM_MOVED = "BUDGET_ITEM_MOVED";

export const BUDGET_ITEM_EXPENSE_NEW = "BUDGET_ITEM_EXPENSE_NEW";
export const BUDGET_ITEM_EXPENSE_CREATED = "BUDGET_ITEM_EXPENSE_CREATED";
export const BUDGET_ITEM_EXPENSE_UPDATED = "BUDGET_ITEM_EXPENSE_UPDATED";
export const BUDGET_ITEM_EXPENSE_REMOVED = "BUDGET_ITEM_EXPENSE_REMOVED";
export const BUDGET_ITEM_EXPENSE_IMPORTED = "BUDGET_ITEM_EXPENSE_IMPORTED";

export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export const LOAD_NET_WORTH_YEAR = "LOAD_NET_WORTH_YEAR";
export const REFRESH_NET_WORTH_YEAR = "REFRESH_NET_WORTH_YEAR";
export const NET_WORTH_YEAR_LOADED = "NET_WORTH_YEAR_LOADED";
export const NET_WORTH_REQUEST_FINISHED = "NET_WORTH_REQUEST_FINISHED";

export const NET_WORTH_ITEMS_IMPORTED = "NET_WORTH_ITEMS_IMPORTED";
export const NET_WORTH_ASSET_ADDED = "NET_WORTH_ASSET_ADDED";
export const NET_WORTH_ASSET_UPDATED = "NET_WORTH_ASSET_UPDATED";
export const NET_WORTH_ASSET_DELETED = "NET_WORTH_ASSET_DELETED";

export const NET_WORTH_ITEM_ADDED = "NET_WORTH_ITEM_ADDED";
export const NET_WORTH_ITEM_UPDATED = "NET_WORTH_ITEM_UPDATED";
export const NET_WORTH_ITEM_DELETED = "NET_WORTH_ITEM_DELETED";
