export const BUDGET_UPDATED = 'BUDGET_UPDATED';
export const BUDGET_CATEGORY_UPDATED = 'BUDGET_CATEGORY_UPDATED';
export const BUDGET_CATEGORY_IMPORTED = 'BUDGET_CATEGORY_IMPORTED';
export const BUDGET_DATE_UPDATED = 'BUDGET_DATE_UPDATED';

export const BUDGET_ITEM_NEW = 'BUDGET_ITEM_NEW';
export const BUDGET_ITEM_SAVED = 'BUDGET_ITEM_SAVED';
export const BUDGET_ITEM_UPDATED = 'BUDGET_ITEM_UPDATED';
export const BUDGET_ITEM_DELETED = 'BUDGET_ITEM_DELETED';
export const BUDGET_ITEM_MOVED = 'BUDGET_ITEM_MOVED';

export const BUDGET_ITEM_EXPENSE_NEW = 'BUDGET_ITEM_EXPENSE_NEW';
export const BUDGET_ITEM_EXPENSE_SAVED = 'BUDGET_ITEM_EXPENSE_SAVED';
export const BUDGET_ITEM_EXPENSE_UPDATED = 'BUDGET_ITEM_EXPENSE_UPDATED';
export const BUDGET_ITEM_EXPENSE_DELETED = 'BUDGET_ITEM_EXPENSE_DELETED';
export const BUDGET_ITEM_EXPENSE_IMPORTED = 'BUDGET_ITEM_EXPENSE_IMPORTED';
export const MORTGAGE_CALCULATOR_UPDATED = 'MORTGAGE_CALCULATOR_UPDATED';

export const ANNUAL_ITEMS_FETCHED = 'ANNUAL_ITEMS_FETCHED';
export const ANNUAL_ITEMS_SHOW_FORM = 'ANNUAL_ITEMS_SHOW_FORM';
export const ANNUAL_ITEMS_HIDE_FORM = 'ANNUAL_ITEMS_HIDE_FORM';
export const ANNUAL_ITEMS_TOGGLE_YEAR_FORM = 'ANNUAL_ITEMS_TOGGLE_YEAR_FORM';
export const ANNUAL_ITEMS_ADDED = 'ANNUAL_ITEMS_ADDED';
export const ANNUAL_ITEMS_UPDATED = 'ANNUAL_ITEMS_UPDATED';
export const ANNUAL_ITEMS_REMOVED = 'ANNUAL_ITEMS_REMOVED';
